server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: itineraire-optimisation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/itineraire_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:anass2002}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Africa/Casablanca
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=3600s
external:
  api:
    nominatim:
      base-url: https://nominatim.openstreetmap.org
      email: contact@transport.com
    osrm:
      base-url: http://router.project-osrm.org
      profile: car
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation123456789
springdoc:
  swagger-ui:
    path: /swagger-ui.html
optimization:
  max-waypoints: 25
  algorithm: heuristic
